name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '10', '8' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm install
    - name: eslint check
      run: npm test
    - name: Build Mattermost environment and create test users
      run: |
          docker pull mattermost/platform && \
          docker run --name mattermost-preview -d --publish 8065:8065 --add-host dockerhost:127.0.0.1 mattermost/mattermost-preview && \
          docker exec mattermost-preview bash -c 'mattermost user create --system_admin --email admin@example.com --username admin --password Admin12345!'

  build_latest:
    name: Node latest
    runs-on: ubuntu-latest
    container: node:latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm install
    - name: eslint check
      run: npm test
